version: '3.1'
services:
  db:
    image: mysql
    container_name: biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - biblioteca_data:/var/lib/mysql

volumes:
  biblioteca_data: